version: 0.2

phases:
  install:
      commands:
      - npm i create-react-app
  build:
    commands:
      - npm run build
artifacts:
  files:
    - **/*
  base-directory: 'build'
  discard-paths: no
